-- Idempotent baseline for a new telemetry database and for the current normalized record fields.
-- Future schema changes must be added as a new, versioned migration rather than changing an applied migration.
CREATE TABLE IF NOT EXISTS "TelemetryRecords" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DeviceId" text NOT NULL,
  "GatewayId" text NULL,
  "AssetId" text NULL,
  "Temperature" double precision NULL,
  "Humidity" double precision NULL,
  "Vibration" double precision NULL,
  "Power" double precision NULL,
  "Pressure" double precision NULL,
  "Rpm" double precision NULL,
  "Timestamp" timestamp with time zone NOT NULL
);

ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "GatewayId" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "AssetId" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Power" double precision NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Pressure" double precision NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Rpm" double precision NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Temperature" DROP NOT NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Humidity" DROP NOT NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Vibration" DROP NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_TelemetryRecords_DeviceId_Timestamp"
  ON "TelemetryRecords" ("DeviceId", "Timestamp" DESC);
