using SmartFactory.BuildingBlocks.DashboardAccess;
using SmartFactory.Services.NotificationService;
var builder = WebApplication.CreateBuilder(args);
builder.AddDashboardAccess();
builder.Services.AddHttpClient("graph", client => client.Timeout = TimeSpan.FromSeconds(30));
builder.Services.AddSingleton<GraphMailSender>(services => new GraphMailSender(services.GetRequiredService<IHttpClientFactory>().CreateClient("graph"), builder.Configuration));
builder.Services.AddHostedService<NotificationDeliveryWorker>();
var app = builder.Build();
app.UseDashboardAccess("SELECT id FROM notification_inbox LIMIT 1");
app.MapGet("/api/notifications/status", (GraphMailSender sender) => Results.Ok(new { emailConfigured = sender.Configured, provider = "Microsoft Graph", delivery = "at-least-once" }));
app.Run();
