apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-factory-device-service
data:
  aas-repository-url: https://aas.replace-with-company-endpoint.invalid
  aas-submodel-repository-url: https://submodels.replace-with-company-endpoint.invalid
  aas-concept-description-repository-url: https://concept-descriptions.replace-with-company-endpoint.invalid
  aas-registry-url: https://aas-registry.replace-with-company-endpoint.invalid
  aas-submodel-registry-url: https://submodel-registry.replace-with-company-endpoint.invalid
  aasx-file-server-url: https://aasx.replace-with-company-endpoint.invalid
  aas-oidc-token-url: ""
  aas-oidc-discovery-url: https://identity.replace-with-company-endpoint.invalid/.well-known/openid-configuration
  aas-oidc-scope: ""
  aas-repository-registry-integration: "true"
  aas-allow-unauthenticated-local: "false"
  mqtt-broker-host: mqtt.replace-with-cloudamqp-host.invalid
  edge-site-id: factory-a
  edge-line-id: line-1
  mqtt-topic: factory/+/+/+/telemetry
  mqtt-client-id: smart-factory-telemetry-production
  internal-telemetry-sink-url: http://smart-factory-dashboard.smart-factory.svc.cluster.local/api/internal/telemetry
  dotnet-log-level: Information
  azure-ad-instance: https://login.microsoftonline.com/
  graph-api-base-url: https://graph.microsoft.com/v1.0
