-- PostgreSQL database is created from POSTGRES_DB by docker-compose.
-- This schema matches TelemetryRecord for local use and can be re-run on an
-- existing installation to add the normalized industrial telemetry fields.
CREATE TABLE IF NOT EXISTS "TelemetryRecords" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "DeviceId" text NOT NULL,
  "GatewayId" text NULL,
  "AssetId" text NULL,
  "Temperature" double precision NULL,
  "Humidity" double precision NULL,
  "Vibration" double precision NULL,
  "Power" double precision NULL,
  "Pressure" double precision NULL,
  "Rpm" double precision NULL,
  "Timestamp" timestamp with time zone NOT NULL
);

ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "AssetId" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "GatewayId" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "SensorType" varchar(64) NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "SensorStatus" varchar(16) NULL;
DO $$
BEGIN
  ALTER TABLE "TelemetryRecords" ADD CONSTRAINT "CK_TelemetryRecords_SensorType_Length"
    CHECK ("SensorType" IS NULL OR char_length("SensorType") BETWEEN 1 AND 64);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$
BEGIN
  ALTER TABLE "TelemetryRecords" ADD CONSTRAINT "CK_TelemetryRecords_SensorStatus"
    CHECK ("SensorStatus" IS NULL OR "SensorStatus" IN ('ok', 'read_error'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Power" double precision NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Pressure" double precision NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "Rpm" double precision NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Temperature" DROP NOT NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Humidity" DROP NOT NULL;
ALTER TABLE "TelemetryRecords" ALTER COLUMN "Vibration" DROP NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_TelemetryRecords_DeviceId_Timestamp"
  ON "TelemetryRecords" ("DeviceId", "Timestamp" DESC);

-- Run after telemetry-schema.sql and before deploying the telemetry worker.
-- Existing records are retained; only new normalized messages enter the outbox.
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "AssetSignalsJson" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "IngestionId" text NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "DashboardForwardedAt" timestamptz NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "NextDeliveryAttemptAt" timestamptz NULL;
ALTER TABLE "TelemetryRecords" ADD COLUMN IF NOT EXISTS "DeliveryAttempts" integer NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TelemetryRecords_IngestionId" ON "TelemetryRecords" ("IngestionId");
DROP INDEX IF EXISTS "IX_TelemetryRecords_PendingDelivery";
CREATE INDEX "IX_TelemetryRecords_PendingDelivery"
  ON "TelemetryRecords" ("NextDeliveryAttemptAt", "Id")
  WHERE "IngestionId" IS NOT NULL AND "DashboardForwardedAt" IS NULL;
